# -*- coding: utf-8 -*-
"""HALM-3AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n7yblKqHDcMfet12-RsbZX65ITnrJMCm

#Halm – Unified Hazard Detection using YOLOv8 (Sharp Tools & Pits)

## 1. Project Overview

This notebook documents the development of a **unified computer vision model** for hazard detection in construction environments. The system detects:

* Sharp tools on the ground (hazard)
* Potholes / pits (hazard)
* Handheld sharp tools (non-hazard)

The model is designed for **edge deployment** on Raspberry Pi and integrated with a helmet-mounted camera.

## 2. Design Decisions & Constraints

* **Single unified model** chosen instead of multiple parallel models to reduce computational overhead.
* **45° camera angle** selected to maximize ground visibility while avoiding false positives from handheld tools.
* **YOLOv8 Nano** used for edge deployment; **YOLOv8 Small** used for benchmarking and comparison.

## 3. Dataset Description

The training dataset is composed of multiple sources:

### 3.1 Sharp Tools Dataset

* Largest dataset
* Contains sharp tools placed on the ground
* High visual diversity
* **Source:** [https://datasetninja.com/small-size-construction-tools#download](https://datasetninja.com/small-size-construction-tools#download)

### 3.2 Pothole / Pit Datasets

* Two datasets combined to increase sample size
* Focused on ground-level hazards
* **Sources:**

  * [https://universe.roboflow.com/rana-7krlb/pits-wqyxv-h510m/browse](https://universe.roboflow.com/rana-7krlb/pits-wqyxv-h510m/browse)
  * [https://www.kaggle.com/datasets/chitholian/annotated-potholes-dataset](https://www.kaggle.com/datasets/chitholian/annotated-potholes-dataset)

### 3.3 Handheld Sharp Tools Dataset

* Smaller dataset (~1600 samples)
* Represents **non-hazard context** where tools are used correctly
* **Source:** [https://universe.roboflow.com/jee-cmmsh/hand-tool-detection-pbu9x/browse](https://universe.roboflow.com/jee-cmmsh/hand-tool-detection-pbu9x/browse) ** where tools are used correctly

## 4. Class Definitions

| Class ID | Description                   |
| -------- | ------------------------------|
| 0        | Sharp tool on ground (Hazard) |
| 1        | Pothole / Pit (Hazard)        |
| 2        | Handheld sharp tool (Safe)    |

## 5. Dataset Challenges

* Noticeable **class imbalance**, with sharp tools being the dominant class
* Imbalance intentionally preserved to reflect real-world distributions

* **Mitigation strategy includes:**

  * Dataset merging for minority classes
  * Data augmentation

----

##6. Implementation

###Step 1 : Environment Setup & Drive Mounting:

This cell installs the necessary engine, imports all libraries, and connects to Google Drive.
"""

# ==========================================
# STEP 1: Dependencies & Drive Integration
# ==========================================

# --- Install the YOLO engine ---
# Ultralytics provides the YOLOv8 framework used for your hazard detection models.
!pip install ultralytics -q

# --- Standard Library & File Management ---

import os                      # Operating system interface (path management, directory creation)
import shutil                  # High-level file operations (moving, copying folders)
import yaml                    # For reading and writing .yaml configuration files (dataset paths)
import zipfile                 # To extract your dataset zip files
import random                  # For shuffling data and random sampling
import glob                    # To find all pathnames matching a specific pattern (useful for file lists)
from datetime import datetime  # For timestamping your model backups and logs

# --- Data Processing & Math ---

import torch                                          # The deep learning framework that runs the models
import numpy as np                                    # For numerical operations on image arrays and IMU data
import pandas as pd                                   # For handling results.csv and metrics analysis
from sklearn.model_selection import train_test_split  # To split data into Train/Val sets

# --- Computer Vision & Imaging ---

import cv2                         # OpenCV for video processing and frame extraction
from PIL import Image              # For basic image opening and resizing
import xml.etree.ElementTree as ET # To parse XML annotation files if using Pascal VOC format

# --- Visualization ---

import matplotlib.pyplot as plt    # Main plotting library for training curves and mAP
import matplotlib.image as mpimg   # To specifically load and display .png result images
import seaborn as sns              # For cleaner statistical visualizations (like confusion matrices)

# --- AI Engine ---

from ultralytics import YOLO       # The specific class to load, train, and test YOLOv8

# --- Google Colab & System Utilities ---

from google.colab import drive     # To mount the Google Drive for persistent storage
from google.colab import files     # To download the .pt model weights locally to your laptop
import subprocess                  # To run system commands (useful for Raspberry Pi setup/FFmpeg)
from IPython.display import display, Image as IPImage, Video, HTML # To display images, training videos, and interactive elements in the notebook

# --- MOUNT DRIVE ---
# This ensures the models are saved to the Drive.
drive.mount('/content/drive')

print("✅ Environment ready, all libraries imported, and Drive mounted.")

"""###Step 2: Workspace Initialization
This cell creates the isolated "Safe Zones" for each dataset. This ensures that we handle each pipeline separately before the final merge.
"""

# ==========================================
# STEP 2: Directory Architecture
# ==========================================

# Define raw data sources and final unified destination
DIRS = [
    '/content/raw_sharp',      # Dataset 1: Sharp Tools (Hazard)
    '/content/raw_pits_1',     # Dataset 2: Potholes (Hazard)
    '/content/raw_pits_2',     # Dataset 3: Potholes (Additional)
    '/content/raw_handheld',   # Dataset 4: Handheld Tools (Safe)
    '/content/halm_final/images/train',
    '/content/halm_final/images/val',
    '/content/halm_final/labels/train',
    '/content/halm_final/labels/val'
]

for d in DIRS:
    os.makedirs(d, exist_ok=True)

print("✅ Isolated directory structure created.")

"""###Step 3: Local Data Extraction
To prevent "Transport endpoint" errors, we move the ZIP files from the cloud (Drive) to the local machine disk before unzipping.
"""

# ==========================================
# STEP 3: High-Speed Local Extraction
# ==========================================

# Mapping Drive paths to local extraction zones
dataset_map = {
    '/content/drive/MyDrive/DATA1 (1).zip': '/content/raw_sharp',
    '/content/drive/MyDrive/pits.v1i.yolov8.zip': '/content/raw_pits_1',
    '/content/drive/MyDrive/archive (1).zip': '/content/raw_pits_2',
    '/content/drive/MyDrive/Hand Tool Detection.v6i.yolov8.zip': '/content/raw_handheld'
}

def fast_extract(zip_path, target_folder):
    if os.path.exists(zip_path):
        # Create a local copy of the ZIP for faster extraction
        local_zip = '/content/temp_extract.zip'
        shutil.copy(zip_path, local_zip)

        with zipfile.ZipFile(local_zip, 'r') as z:
            z.extractall(target_folder)

        os.remove(local_zip) # Remove temp file
        print(f"✅ Extracted: {os.path.basename(zip_path)}")
    else:
        print(f"❌ File not found: {zip_path}")

# Run extraction
for drive_path, local_folder in dataset_map.items():
    fast_extract(drive_path, local_folder)

"""###Step 4: Multi-Dataset Visual Validation
Before merging, we must see the data to ensure the bounding boxes align. We will create a helper function to visualize 3 random images from any directory.
"""

# ==========================================
# STEP 4: Visual Validation
# ==========================================

def visualize_sample(img_dir, lbl_dir, num_samples=3):
    """Helper function to plot images with bounding boxes."""
    image_files = [f for f in os.listdir(img_dir) if f.lower().endswith(('.jpg', '.png', '.jpeg'))]
    if not image_files:
        print(f"No images found in {img_dir}")
        return

    samples = random.sample(image_files, min(num_samples, len(image_files)))
    fig, axes = plt.subplots(1, len(samples), figsize=(18, 6))
    if len(samples) == 1: axes = [axes]

    for i, img_name in enumerate(samples):
        img_path = os.path.join(img_dir, img_name)
        # Assuming labels are in a parallel 'labels' or 'annotated-labels' folder
        lbl_name = img_name.rsplit('.', 1)[0] + '.txt'
        lbl_path = os.path.join(lbl_dir, lbl_name)

        img = cv2.imread(img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        h, w, _ = img.shape

        if os.path.exists(lbl_path):
            with open(lbl_path, 'r') as f:
                for line in f:
                    parts = line.split()
                    if len(parts) < 5: continue
                    cls, x, y, bw, bh = map(float, parts[:5])
                    x1, y1 = int((x - bw/2) * w), int((y - bh/2) * h)
                    x2, y2 = int((x + bw/2) * w), int((y + bh/2) * h)
                    cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 3)

        axes[i].imshow(img)
        axes[i].set_title(f"Verify: {img_name}")
        axes[i].axis('off')
    plt.show()


configs = [
    {
        'name': '1. Sharp Tools (Hazard)',
        'img_dir': '/content/raw_sharp/DATA1',
        'lbl_dir': '/content/raw_sharp/labels'
    },
    {
        'name': '2. Potholes Dataset A',
        'img_dir': '/content/raw_pits_1/train/images',
        'lbl_dir': '/content/raw_pits_1/train/labels'
    },
    {
        'name': '3. Potholes Dataset B',
        'img_dir': '/content/raw_pits_2/annotated-images',
        'lbl_dir': '/content/raw_pits_2/labels'
    },
    {
        'name': '4. Handheld Tools (Safe)',
        'img_dir': '/content/raw_handheld/train/images',
        'lbl_dir': '/content/raw_handheld/train/labels'
    }
]

def verify_all_datasets(dataset_configs):
    for config in dataset_configs:
        print(f"\n🔍 VALIDATING: {config['name']}")
        if os.path.exists(config['img_dir']):
            visualize_sample(config['img_dir'], config['lbl_dir'], num_samples=3)
        else:
            print(f"⚠️ Path not found: {config['img_dir']}")

verify_all_datasets(configs)

"""###STEP 5: Unified Remapping & Master Merge
In this cell, we scan all raw folders and move the images/labels into our unified halm_final directory. We perform a final "Garbage Filter" to ensure those non-normalized coordinates (the ones that cause training spikes) are deleted.

This function below is essential for **Dataset Unification**. Since  Halm project combines different hazard sources, they must all use the same "language."

* **Format Translation:** the Pothole dataset uses XML (PascalVOC), but YOLOv8 only reads TXT files.

* **Coordinate Scaling:** It converts raw pixel coordinates (e.g., xmin: 50) into Normalized Decimals (0.0 to 1.0) relative to the image size.

* **Data Integration:** It allows the model to learn from the pothole data alongside your sharp tool data, ensuring the "Small" and "Nano" models can detect both hazards simultaneously.
"""

# ==========================================
# STEP 5.1: Unified Remapping
# ==========================================

def convert_voc_to_yolo(xml_dir, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    count = 0
    for xml_file in os.listdir(xml_dir):
        if not xml_file.endswith('.xml'): continue

        tree = ET.parse(os.path.join(xml_dir, xml_file))
        root = tree.getroot()
        size = root.find('size')
        w = int(size.find('width').text)
        h = int(size.find('height').text)

        yolo_lines = []
        for obj in root.iter('object'):
            xmlbox = obj.find('bndbox')
            xmin, xmax = float(xmlbox.find('xmin').text), float(xmlbox.find('xmax').text)
            ymin, ymax = float(xmlbox.find('ymin').text), float(xmlbox.find('ymax').text)

            x_center = (xmin + xmax) / 2.0 / w
            y_center = (ymin + ymax) / 2.0 / h
            width = (xmax - xmin) / w
            height = (ymax - ymin) / h
            yolo_lines.append(f"1 {x_center} {y_center} {width} {height}")

        with open(os.path.join(out_dir, xml_file.replace('.xml', '.txt')), 'w') as f:
            f.write("\n".join(yolo_lines))
        count += 1
    print(f"✅ Converted {count} XML files to YOLO format in {out_dir}")

convert_voc_to_yolo('/content/raw_pits_2/annotated-images', '/content/raw_pits_2/labels')

# ==========================================
# STEP 5.2: FINAL Unified Master Merge
# ==========================================

def process_and_merge_all(configs, split='train'):
    dest_img_dir = f'/content/halm_final/images/{split}'
    dest_lbl_dir = f'/content/halm_final/labels/{split}'
    os.makedirs(dest_img_dir, exist_ok=True)
    os.makedirs(dest_lbl_dir, exist_ok=True)

    for config in configs:
        name = config['name']
        src_img_dir = config['img_dir']
        src_lbl_dir = config['lbl_dir']
        new_id = config['new_id']
        is_sharp_tool = config.get('is_sharp_tool', False)

        print(f"\n🚀 Processing {name} (Class {new_id})...")
        count = 0
        rejected = 0

        img_files = [f for f in os.listdir(src_img_dir) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]

        for img_name in img_files:
            stem = img_name.rsplit('.', 1)[0]
            img_path = os.path.join(src_img_dir, img_name)
            lbl_path = os.path.join(src_lbl_dir, stem + '.txt')

            if not os.path.exists(lbl_path): continue

            img = cv2.imread(img_path)
            if img is None: continue
            img_h, img_w, _ = img.shape

            with open(lbl_path, 'r') as f:
                lines = f.readlines()

            valid_yolo_lines = []
            for line in lines:
                line = line.replace(',', ' ').strip()
                parts = line.split()
                if not parts: continue

                try:
                    if is_sharp_tool:
                        # Pixel to YOLO logic for Class 0
                        x_min, y_min, px_w, px_h = map(float, parts[:4])
                        x_c = (x_min + (px_w / 2)) / img_w
                        y_c = (y_min + (px_h / 2)) / img_h
                        w_norm, h_norm = px_w / img_w, px_h / img_h
                    else:
                        # Standard YOLO logic for Class 1 & 2
                        vals = [float(x) for x in parts]
                        x_c, y_c, w_norm, h_norm = vals[1:5] if len(vals) == 5 else vals[0:4]

                    if 0 <= x_c <= 1 and 0 <= y_c <= 1:
                        valid_yolo_lines.append(f"{new_id} {x_c:.6f} {y_c:.6f} {w_norm:.6f} {h_norm:.6f}")
                    else:
                        rejected += 1
                except: rejected += 1

            if valid_yolo_lines:
                shutil.copy(img_path, os.path.join(dest_img_dir, img_name))
                with open(os.path.join(dest_lbl_dir, stem + '.txt'), 'w') as f_out:
                    f_out.write("\n".join(valid_yolo_lines))
                count += 1
        print(f"✅ {name}: Successfully merged {count} images.")

# Define all datasets to be merged
dataset_configs = [
    {'name': 'Sharp Tools (Hazard)', 'img_dir': '/content/raw_sharp/DATA1', 'lbl_dir': '/content/raw_sharp/DATA1', 'new_id': 0, 'is_sharp_tool': True},
    {'name': 'Potholes A', 'img_dir': '/content/raw_pits_1/train/images', 'lbl_dir': '/content/raw_pits_1/train/labels', 'new_id': 1},
    {'name': 'Potholes B', 'img_dir': '/content/raw_pits_2/annotated-images', 'lbl_dir': '/content/raw_pits_2/labels', 'new_id': 1},
    {'name': 'Handheld Safe', 'img_dir': '/content/raw_handheld/train/images', 'lbl_dir': '/content/raw_handheld/train/labels', 'new_id': 2}
]

process_and_merge_all(dataset_configs)

"""###STEP 6: Final Distribution Analysis"""

# ==========================================
# STEP 6.1: Final Class Distribution
# ==========================================

def get_eda_dataframe():
    lbl_dir = '/content/halm_final/labels/train'
    data = []
    for lbl in os.listdir(lbl_dir):
        with open(os.path.join(lbl_dir, lbl), 'r') as f:
            for line in f:
                parts = line.split()
                if len(parts) < 5: continue
                cls, x, y, w, h = map(float, parts)
                data.append({'class': int(cls), 'x': x, 'y': y, 'w': w, 'h': h, 'area': w * h})

    df = pd.DataFrame(data)
    names = {0: 'Sharp Tool (Hazard)', 1: 'Pothole (Hazard)', 2: 'Handheld Tool (Safe)'}
    df['name'] = df['class'].map(names)
    return df

df_eda = get_eda_dataframe()

plt.figure(figsize=(10, 6))
sns.countplot(data=df_eda, x='name', palette='viridis')
plt.title("Step 6.1: Unified Dataset Class Balance")
plt.xticks(rotation=15)
plt.show()

print(f"Total labeled objects: {len(df_eda)}")
print(df_eda['name'].value_counts())

# ==========================================
# STEP 6.2: Object Area Distribution
# ==========================================
plt.figure(figsize=(10, 6))
sns.boxplot(data=df_eda, x='name', y='area', palette='coolwarm')
plt.yscale('log') # Log scale because pixels vary wildly between tools and pits
plt.title("Step 6.2: Relative Object Area (Log Scale)")
plt.ylabel("Normalized Area (Object Size / Image Size)")
plt.show()

# Calculate Mean Area for the report
mean_areas = df_eda.groupby('name')['area'].mean()
print("📊 Mean Relative Area per Class:")
print(mean_areas)

# ==========================================
# STEP 6.3: Spatial Heatmap of Detections
# ==========================================
plt.figure(figsize=(10, 8))
hb = plt.hexbin(df_eda['x'], df_eda['y'], gridsize=25, cmap='YlOrRd', bins='log')
plt.title("Step 6.3: Spatial Density Heatmap (Hazard Zones)")
plt.xlabel("X-Center (Normalized)")
plt.ylabel("Y-Center (Normalized)")
plt.gca().invert_yaxis() # Invert to match image coordinate system (top is 0)
plt.colorbar(hb, label='Log10(Count)')
plt.show()

# ==========================================
# STEP 6.4: Aspect Ratio Analysis
# ==========================================
df_eda['aspect_ratio'] = df_eda['w'] / (df_eda['h'] + 1e-6)

plt.figure(figsize=(10, 6))
sns.violinplot(data=df_eda, x='name', y='aspect_ratio', inner="quartile", palette='muted')
plt.ylim(0, 5) # Cut off extreme outliers for visibility
plt.title("Step 6.4: Aspect Ratio Distribution (Width/Height)")
plt.axhline(1, color='red', linestyle='--', alpha=0.5) # Square reference line
plt.show()

"""###STEP 7: YAML Configuration"""

# ==========================================
# STEP 7: Generate data.yaml
# ==========================================


# Define the dataset mapping
# Class 0: Sharp Tools (Hazard)
# Class 1: Potholes (Hazard)
# Class 2: Handheld Tools (Safe - Negative Class)

yaml_content = {
    'train': '/content/halm_final/images/train',
    'val': '/content/halm_final/images/train', # We will use the same for now or split later
    'nc': 3,
    'names': [
        'Sharp Tool (Hazard)',
        'Pothole (Hazard)',
        'Handheld Tool (Safe)'
    ]
}

# Write the file to the workspace
with open('/content/halm_final/data.yaml', 'w') as f:
    yaml.dump(yaml_content, f, default_flow_style=False)

print("✅ Step 7 Complete: data.yaml created.")
print("--- YAML Content ---")
with open('/content/halm_final/data.yaml', 'r') as f:
    print(f.read())

"""###STEP 8: Model Training (YOLOv8 Nano)"""

# ==========================================
# STEP 8.1: Train the Nano Model (YOLOv8s)
# ==========================================

# 1. Load the YOLOv8 Nano model (pre-trained on COCO)
model = YOLO('yolov8n.pt')

# 2. Train the model
results = model.train(
    data='/content/halm_final/data.yaml',
    epochs=50,
    imgsz=640,
    batch=-1,                     # Auto batch size
    patience=10,                  # Early stopping
    device=0 if torch.cuda.is_available() else 'cpu',
    project='/content/drive/MyDrive/HALM_YOLO',  # FORCE save to Drive
    name='halm_hazard_nano'        # Clear experiment name
)

print("🚀 Training complete!")
print("📁 Best model saved at:")
print("/content/drive/MyDrive/HALM_YOLO/halm_hazard_nano/weights/best.pt")

# ==========================================
# STEP 8.2 : Download Nano Model Locally
# ==========================================

nano_model_path = '/content/drive/MyDrive/HALM_YOLO/halm_hazard_nano3/weights/best.pt'

if os.path.exists(nano_model_path):
    print(f"✅ Found Nano model in Drive. Starting download...")
    files.download(nano_model_path)
else:
    # Fallback: Check the local Colab folder if Drive hasn't synced yet
    local_path = '/content/runs/detect/halm_hazard_nano3/weights/best.pt'
    if os.path.exists(local_path):
        print(f"✅ Found local Nano model. Starting download...")
        files.download(local_path)
    else:
        print("❌ Error: 'best.pt' not found. Please verify the folder name in your Google Drive.")

"""###STEP 9: Model Training (YOLOv8 Small)"""

# ==========================================
# STEP 9.1: Train the Small Model (YOLOv8s)
# ==========================================

# 1. Load the YOLOv8 Small model (pre-trained on COCO)
# This model is larger and more accurate than the Nano version
model = YOLO('yolov8s.pt')

# 2. Start Training
# imgsz: 640 is standard.
# batch: -1 lets YOLO choose the best size for your Colab GPU.
results = model.train(
    data='/content/halm_final/data.yaml',
    epochs=60,
    imgsz=640,
    batch=-1,
    name='halm_hazard_small_v1', # Updated name to keep runs separate
    patience=10,                 # Early stopping if no improvement
    device=0                     # Use GPU
)

print("🚀 Training complete! Small model weights saved in: runs/detect/halm_hazard_small_v1/weights/best.pt")

# ==========================================
# STEP 9.1: Download Small Model from Drive
# ==========================================

small_model_path = '/content/drive/MyDrive/Halm_Small_Backup/weights/best.pt'

if os.path.exists(small_model_path):
    print(f"✅ Found Small model at: {small_model_path}")
    print("🚀 Starting download to your laptop...")
    files.download(small_model_path)
else:
    print("❌ Error: Path not found. Please ensure your Drive is still mounted.")

"""###STEP 10: YOLOv8 Nano Performance Testing on unseen data

Step 10.1: Nano Model - Sharp Tools (Hazard)
"""

# ==========================================
# STEP 10.1: Nano Model - Sharp Tools (Hazard)
# ==========================================

model_nano = YOLO("/content/drive/MyDrive/HALM_YOLO/halm_hazard_nano3/weights/best.pt")
videos = ["testsharp.mp4", "test2sharp.mp4"]
base_path = "/content/drive/MyDrive/"

for v in videos:
    v_path = os.path.join(base_path, v)
    if os.path.exists(v_path):
        print(f"🚀 Nano Predicting: {v}")
        model_nano.predict(source=v_path, imgsz=640, conf=0.4, save=True, device=0)

        # Get latest predict folder
        latest_dir = max(glob.glob('runs/detect/predict*/'), key=os.path.getmtime)
        raw_avi = os.path.join(latest_dir, v.replace('.mp4', '.avi'))
        out_mp4 = os.path.join(latest_dir, f"nano_{v}")

        # Convert for display
        subprocess.run(f"ffmpeg -i {raw_avi} -vcodec libx264 -f mp4 {out_mp4} -y", shell=True, capture_output=True)
        display(HTML(f"<h4>Nano Result: {v}</h4>"))
        display(Video(out_mp4, embed=True, width=700))

"""Step 10.2: Nano Model - Handheld Tools (Safe)"""

# =============================================
# STEP 10.2: Nano Model - Handheld Tools (Safe)
# =============================================

v_name = "test3sharp.mp4"
v_path = f"/content/drive/MyDrive/{v_name}"

print(f"🚀 Nano Predicting Safe Class: {v_name}")
model_nano.predict(source=v_path, imgsz=640, conf=0.4, save=True, device=0)

latest_dir = max(glob.glob('runs/detect/predict*/'), key=os.path.getmtime)
raw_avi = os.path.join(latest_dir, v_name.replace('.mp4', '.avi'))
out_mp4 = os.path.join(latest_dir, f"nano_safe_{v_name}")

subprocess.run(f"ffmpeg -i {raw_avi} -vcodec libx264 -f mp4 {out_mp4} -y", shell=True, capture_output=True)
display(HTML(f"<h4>Nano Safe Detection: {v_name}</h4>"))
display(Video(out_mp4, embed=True, width=700))

"""Step 10.3: Nano Model - Pitfalls (Hazard)"""

# ==========================================
# STEP 10.3: Nano Model - Pitfalls (Hazard)
# ==========================================

v_name = "pit_test.mp4"
v_path = f"/content/drive/MyDrive/{v_name}"

print(f"🚀 Nano Predicting Potholes: {v_name}")
model_nano.predict(source=v_path, imgsz=640, conf=0.4, save=True, device=0)

latest_dir = max(glob.glob('runs/detect/predict*/'), key=os.path.getmtime)
raw_avi = os.path.join(latest_dir, v_name.replace('.mp4', '.avi'))
out_mp4 = os.path.join(latest_dir, f"nano_pit_{v_name}")

subprocess.run(f"ffmpeg -i {raw_avi} -vcodec libx264 -f mp4 {out_mp4} -y", shell=True, capture_output=True)
display(HTML(f"<h4>Nano Pitfall Result: {v_name}</h4>"))
display(Video(out_mp4, embed=True, width=700))

"""###PART 11: YOLOv8 Small Performance Testing

We used the exact same logic but load the Halm_Small_Backup model.

11.1: Small Model - Sharp Tools
"""

# ============================================
# STEP 11.1: Small Model - Sharp Tools (Hazard)
# =============================================

model_small = YOLO("/content/drive/MyDrive/Halm_Small_Backup/weights/best.pt")
videos = ["testsharp.mp4", "test2sharp.mp4"]
base_path = "/content/drive/MyDrive/"

for v in videos:
    v_path = os.path.join(base_path, v)
    if os.path.exists(v_path):
        print(f"🚀 Small Predicting: {v}")
        model_small.predict(source=v_path, imgsz=640, conf=0.4, save=True, device=0)

        # Get latest predict folder
        latest_dir = max(glob.glob('runs/detect/predict*/'), key=os.path.getmtime)
        raw_avi = os.path.join(latest_dir, v.replace('.mp4', '.avi'))
        out_mp4 = os.path.join(latest_dir, f"nano_{v}")

        # Convert for display
        subprocess.run(f"ffmpeg -i {raw_avi} -vcodec libx264 -f mp4 {out_mp4} -y", shell=True, capture_output=True)
        display(HTML(f"<h4>Nano Result: {v}</h4>"))
        display(Video(out_mp4, embed=True, width=700))

"""11.2: Nano Model - Handheld Tools (Safe)"""

# ==============================================
# STEP 11.2: Small Model - Handheld Tools (Safe)
# ==============================================

v_name = "test3sharp.mp4"
v_path = f"/content/drive/MyDrive/{v_name}"

print(f"🚀 Small Predicting Safe Class: {v_name}")
model_small.predict(source=v_path, imgsz=640, conf=0.4, save=True, device=0)

latest_dir = max(glob.glob('runs/detect/predict*/'), key=os.path.getmtime)
raw_avi = os.path.join(latest_dir, v_name.replace('.mp4', '.avi'))
out_mp4 = os.path.join(latest_dir, f"nano_safe_{v_name}")

subprocess.run(f"ffmpeg -i {raw_avi} -vcodec libx264 -f mp4 {out_mp4} -y", shell=True, capture_output=True)
display(HTML(f"<h4>Nano Safe Detection: {v_name}</h4>"))
display(Video(out_mp4, embed=True, width=700))

"""Step 11.3: Nano Model - Pitfalls (Hazard)"""

# ==========================================
# STEP 11.3: Small Model - Pitfalls (Hazard)
# ==========================================

v_name = "pit_test.mp4"
v_path = f"/content/drive/MyDrive/{v_name}"

print(f"🚀 Small Predicting Potholes: {v_name}")
model_small.predict(source=v_path, imgsz=640, conf=0.4, save=True, device=0)

latest_dir = max(glob.glob('runs/detect/predict*/'), key=os.path.getmtime)
raw_avi = os.path.join(latest_dir, v_name.replace('.mp4', '.avi'))
out_mp4 = os.path.join(latest_dir, f"nano_pit_{v_name}")

subprocess.run(f"ffmpeg -i {raw_avi} -vcodec libx264 -f mp4 {out_mp4} -y", shell=True, capture_output=True)
display(HTML(f"<h4>Nano Pitfall Result: {v_name}</h4>"))
display(Video(out_mp4, embed=True, width=700))

"""###STEP 12: Performance & Metrics Analysis

> **12.1: YOLOv8 Nano Metrics**

This step visualizes the internal performance data for the Nano model.
"""

# ==========================================
# STEP 12.1.1: Nano Model - Confusion Matrix
# ==========================================

nano_dir = '/content/drive/MyDrive/HALM_YOLO/halm_hazard_nano3/'
cm_path = os.path.join(nano_dir, 'confusion_matrix.png')

if os.path.exists(cm_path):
    plt.figure(figsize=(10, 8))
    plt.imshow(mpimg.imread(cm_path))
    plt.title("YOLOv8 Nano: Confusion Matrix", fontsize=16)
    plt.axis('off')
    plt.show()
else:
    print(f"⚠️ Confusion matrix not found in {nano_dir}")

# ==========================================
# STEP 12.1.2: Nano Model - Training Results
# ==========================================
results_path = os.path.join(nano_dir, 'results.png')

if os.path.exists(results_path):
    plt.figure(figsize=(12, 10))
    plt.imshow(mpimg.imread(results_path))
    plt.title("YOLOv8 Nano: Loss & mAP Trends", fontsize=16)
    plt.axis('off')
    plt.show()
else:
    print(f"⚠️ Results trends not found in {nano_dir}")

"""> **12.2: YOLOv8 Small Metrics**

This step repeats the evaluation for the Small model to provide an accuracy baseline.
"""

# ==========================================
# STEP 12.2.1: Small Model - Confusion Matrix
# ==========================================

small_dir = '/content/drive/MyDrive/Halm_Small_Backup/'
cm_path_s = os.path.join(small_dir, 'confusion_matrix.png')

if os.path.exists(cm_path_s):
    plt.figure(figsize=(10, 8))
    plt.imshow(mpimg.imread(cm_path_s))
    plt.title("YOLOv8 Small: Confusion Matrix", fontsize=16)
    plt.axis('off')
    plt.show()
else:
    print(f"⚠️ Confusion matrix not found in {small_dir}")

# ==========================================
# STEP 12.2.2: Small Model - Training Results
# ==========================================
results_path_s = os.path.join(small_dir, 'results.png')

if os.path.exists(results_path_s):
    plt.figure(figsize=(12, 10))
    plt.imshow(mpimg.imread(results_path_s))
    plt.title("YOLOv8 Small: Loss & mAP Trends", fontsize=16)
    plt.axis('off')
    plt.show()
else:
    print(f"⚠️ Results trends not found in {small_dir}")

"""###STEP 13: Final Side-by-Side Benchmarking"""

# ==========================================
# STEP 13: Final Accuracy Benchmarking
# ==========================================

dn = pd.read_csv('/content/drive/MyDrive/HALM_YOLO/halm_hazard_nano3/results.csv')
ds = pd.read_csv('/content/drive/MyDrive/Halm_Small_Backup/results.csv')

dn.columns = dn.columns.str.strip()
ds.columns = ds.columns.str.strip()

plt.figure(figsize=(10, 6))
plt.plot(dn['epoch'], dn['metrics/mAP50(B)'], label='Nano Model (Edge)')
plt.plot(ds['epoch'], ds['metrics/mAP50(B)'], label='Small Model (Reference)')
plt.title("Comparison: mAP@50 Accuracy Over Time", fontsize=14)
plt.xlabel("Epoch")
plt.ylabel("Accuracy (mAP)")
plt.legend()
plt.grid(True)
plt.show()

# ==========================================
# STEP 13.2: Edge Performance Benchmarking
# ==========================================
import time

def benchmark_model(model_path, name):
    model = YOLO(model_path)
    # Get model file size in MB
    file_size = os.path.getsize(model_path) / (1024 * 1024)

    # Measure inference time on a sample image (using CPU to simulate Raspberry Pi better)
    img = np.zeros((640, 640, 3), dtype=np.uint8)
    start_time = time.time()
    for _ in range(10):  # Run 10 times for average
        model.predict(img, device='cpu', verbose=False)
    avg_inference = (time.time() - start_time) / 10 * 1000 # in ms

    return {"Model": name, "Size (MB)": f"{file_size:.2f}", "Latency (ms)": f"{avg_inference:.2f}"}

# Run benchmark
nano_perf = benchmark_model("/content/drive/MyDrive/HALM_YOLO/halm_hazard_nano3/weights/best.pt", "Nano")
small_perf = benchmark_model("/content/drive/MyDrive/Halm_Small_Backup/weights/best.pt", "Small")

# Display as a clean table
perf_df = pd.DataFrame([nano_perf, small_perf])
display(HTML("<h3>🚀 Deployment Trade-off Analysis</h3>"))
display(perf_df)

# ==========================================
# STEP 13.3: Per-Class Accuracy Comparison
# ==========================================

# 1. Manually entered from A100 Validation Logs
# Order: [Sharp Tool, Pothole, Handheld Tool]
nano_map = [0.993, 0.970, 0.988]   # Overall mAP50: 0.984
small_map = [0.994, 0.990, 0.994]  # Overall mAP50: 0.993

classes = ['Sharp Tool (Hazard)', 'Pothole (Hazard)', 'Handheld Tool (Safe)']

# 2. Plotting the Bar Chart
x = np.arange(len(classes))
width = 0.35

fig, ax = plt.subplots(figsize=(12, 7))
rects1 = ax.bar(x - width/2, nano_map, width, label='YOLOv8 Nano', color='#3498db')
rects2 = ax.bar(x + width/2, small_map, width, label='YOLOv8 Small', color='#e67e22')

ax.set_ylabel('mAP@50 Accuracy', fontsize=12)
ax.set_title('Per-Class Accuracy Comparison: Nano vs Small', fontsize=16, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(classes, fontsize=11)
ax.set_ylim(0.9, 1.05)
ax.legend(loc='lower right')

def autolabel(rects):
    for rect in rects:
        height = rect.get_height()
        ax.annotate(f'{height:.3f}',
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, 3),
                    textcoords="offset points",
                    ha='center', va='bottom', fontsize=10, fontweight='bold')

autolabel(rects1)
autolabel(rects2)

fig.tight_layout()
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.show()

"""###Final Safety Backup Cell"""

# ==========================================
# FINAL SAFETY CHECK: Drive & Local Backup
# ==========================================

# 1. Define Verified Paths
nano_path = '/content/drive/MyDrive/HALM_YOLO/halm_hazard_nano3/weights/best.pt'
small_path = '/content/drive/MyDrive/Halm_Small_Backup/weights/best.pt'

# 2. Backup Nano Model
print("🔍 Checking Nano Model...")
if os.path.exists(nano_path):
    print("✅ Nano exists in Drive. Downloading to laptop...")
    files.download(nano_path)
else:
    print("❌ ERROR: Nano model not found in Drive! Check your 'nano3' folder.")

# 3. Backup Small Model
print("\n🔍 Checking Small Model...")
if os.path.exists(small_path):
    print("✅ Small exists in Drive. Downloading to laptop...")
    files.download(small_path)
else:
    print("❌ ERROR: Small model not found in Drive! Check your 'Halm_Small_Backup' folder.")

print("\n🚀 If the download windows appeared, you are 100% safe to close Colab.")